#!/bin/sh
# File: /etc/mirror/scripts/fedora-updates
#

source /etc/mirror/inc/rsync

rmirror mirror.lstn.net::fedora-enchilada/updates fedora/linux/updates '[89]/' '1[0-9]/' 20/ testing/ */ppc */ppc64 */armhfp
