#!/bin/sh
# File: /etc/mirror/scripts/fedora-releases
#

source /usr/share/mirror/inc/rsync

rmirror mirrors.kernel.org::fedora/releases fedora/linux/releases 21/ 22/ 23/ test/ */Live */debug */armhfp

